name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  mingw:
    runs-on: windows-2019
    strategy:
      matrix:
        architecture: [x64, x86]

    steps:
      - uses: actions/checkout@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.architecture }}
      - name: Run CMake
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug 
      - name: Build
        run: cmake --build build --parallel 10

  msvc2019:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} -DCMAKE_CXX_FLAGS="/EHsc"
      if: matrix.build_type == 'Release'
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -A ${{ matrix.architecture }} -DCMAKE_CXX_FLAGS="/EHsc"
      if: matrix.build_type == 'Debug'
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 10

  msvc2019_latest:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 16 2019" -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /EHsc"
    - name: Build
      run: cmake --build build --config Release --parallel 10

  msvc2022:
    runs-on: windows-2022
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [Win32, x64]

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DCMAKE_CXX_FLAGS="/EHsc"
      if: matrix.build_type == 'Release'
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DCMAKE_CXX_FLAGS="/EHsc"
      if: matrix.build_type == 'Debug'
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --parallel 10

  msvc2022_latest:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_CXX_FLAGS="/permissive- /std:c++latest /EHsc"
    - name: Build
      run: cmake --build build --config Release --parallel 10

